import { Dimensions, StyleSheet } from "react-native";

export const ss = StyleSheet.create({
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 32,
  },
  toolbar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  boardSelectorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  boardSelectorBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  boardSelectorText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
  },
  boardIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  boardDropdown: {
    borderRadius: 14,
    padding: 12,
    minWidth: 220,
    maxWidth: 300,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  boardDropdownTitle: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  boardDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    marginBottom: 2,
  },
  boardDropdownItemText: {
    flex: 1,
    fontSize: 14,
  },
  addColumnBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    borderWidth: 1.5,
    borderRadius: 8,
    borderStyle: "dashed",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  addColumnBtnText: {
    fontSize: 13,
    fontWeight: "600",
  },
  columnsContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 12,
  },
  column: {
    borderRadius: 16,
    marginRight: 4,
    maxHeight: Dimensions.get("window").height * 0.68,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    overflow: "hidden",
  },
  columnHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderLeftWidth: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  columnHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  columnHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  columnColorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  columnTitle: {
    fontSize: 14,
    fontWeight: "700",
    flex: 1,
  },
  columnCount: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  columnCountText: {
    fontSize: 11,
    fontWeight: "600",
  },
  columnAddBtn: {
    minHeight: 28,
    borderRadius: 8,
    paddingHorizontal: 8,
    alignItems: "center",
    flexDirection: "row",
    gap: 3,
    justifyContent: "center",
  },
  columnAddText: {
    fontSize: 12,
    fontWeight: "700",
  },
  columnTopAddBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginHorizontal: 10,
    marginTop: 10,
    paddingVertical: 8,
    borderWidth: 1.2,
    borderRadius: 9,
    borderStyle: "dashed",
  },
  columnTopAddText: {
    fontSize: 12,
    fontWeight: "700",
  },
  columnMenuBtn: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyColumnHint: {
    alignItems: "center",
    padding: 20,
  },
  emptyColumnText: {
    fontSize: 13,
    fontStyle: "italic",
  },
  cardItem: {
    flexDirection: "row",
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 12,
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    overflow: "hidden",
  },
  cardColorBar: {
    width: 3,
  },
  cardBody: {
    flex: 1,
    padding: 10,
    gap: 5,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  cardTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  cardDesc: {
    fontSize: 12,
    lineHeight: 16,
  },
  cardMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  cardDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  cardDateText: {
    fontSize: 11,
  },
  cardAvatarRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarOverlap: {
    borderWidth: 1.5,
    borderRadius: 999,
  },
  moreAvatars: {
    fontSize: 10,
    marginLeft: 4,
  },
  cardFooter: {
    flexDirection: "row",
    gap: 10,
  },
  cardFooterItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  cardFooterText: {
    fontSize: 11,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "600",
  },
  avatarBubble: {
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontWeight: "700",
  },
  menuOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  menuPopup: {
    borderRadius: 14,
    padding: 8,
    minWidth: 200,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 10,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 8,
  },
  menuItemText: {
    fontSize: 14,
    flex: 1,
  },
  menuDivider: {
    height: StyleSheet.hairlineWidth,
    marginVertical: 4,
  },
  bottomSheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  bottomSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 36,
    maxHeight: "85%",
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 16,
    textAlign: "center",
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 12,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 4,
  },
  colorPalette: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 4,
  },
  colorDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  colorDotSelected: {
    borderWidth: 3,
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  sheetBtnRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  sheetBtnCancel: {
    flex: 1,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  sheetBtnCancelText: {
    fontSize: 14,
    fontWeight: "600",
  },
  sheetBtnSave: {
    flex: 2,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  sheetBtnSaveText: {
    fontSize: 14,
    fontWeight: "700",
  },
  cardModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  cardModalSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "92%",
    paddingTop: 16,
    paddingBottom: 36,
  },
  cardModalTabs: {
    flexDirection: "row",
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginBottom: 8,
    paddingHorizontal: 16,
  },
  cardModalTab: {
    paddingHorizontal: 8,
    paddingBottom: 12,
    marginRight: 24,
  },
  cardModalTabText: {
    fontSize: 14,
    fontWeight: "600",
  },
  pickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 4,
  },
  pickerBtnText: {
    flex: 1,
    fontSize: 14,
  },
  dateRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  userChip: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  userChipText: {
    fontSize: 12,
    fontWeight: "600",
  },
  deleteBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  commentItem: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    alignItems: "flex-start",
  },
  commentBody: {
    flex: 1,
    gap: 2,
  },
  commentAuthor: {
    fontSize: 13,
    fontWeight: "700",
  },
  commentText: {
    fontSize: 13,
    lineHeight: 18,
  },
  commentDate: {
    fontSize: 11,
  },
  commentInputRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    marginTop: 16,
  },
  commentSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
  },
  emptySubtitle: {
    fontSize: 14,
    textAlign: "center",
  },
  emptyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 8,
  },
  emptyBtnText: {
    fontSize: 14,
    fontWeight: "700",
  },
});
